configservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/config-service
    tag: 0.2.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8888
    targetPort: 8888
    namespace: nmdung-helm


discoveryservice:
  replicaCount: 4
  image:
    repository: nguyenmanhdung/discovery-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8761
    targetPort: 8761
    namespace: nmdung-helm


monitorservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/monitor-admin
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8086
    targetPort: 8086
    namespace: nmdung-helm

gatewayservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/gateway-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8085
    targetPort: 8085
    namespace: nmdung-helm


zipkinservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/zipkin
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 9411
    targetPort: 9411
    namespace: nmdung-helm


mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3306
    targetPort: 3306
    namespace: nmdung-helm


authservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/auth-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8082
    targetPort: 8082
    namespace: nmdung-helm

userservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/user-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8087
    targetPort: 8087
    namespace: nmdung-helm


notificationservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/notification-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8084
    targetPort: 8084
    namespace: nmdung-helm


statisticservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/statistic1-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8088
    targetPort: 8088
    namespace: nmdung-helm

resources: 
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "512Mi" 
    cpu: "500m"

autoscaling:
  enabled: true
  min: 1
  max: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30






