apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-access
spec:
  podSelector:
    matchLabels:
      app: mysql
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - {key: app, operator: In, values: [auth-service-deploy, user-service-deploy]}
    ports:
    - protocol: TCP
      port: 3306   
