apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-micro-helm
  namespace: micro
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: micro.devops2.vn
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: zipkin-service-service
                port:
                  number: 9411
    - host: micro-monitor.devops2.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086
    - host: micro-discovery.devops2.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
    - host: micro-user.devops2.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 8087
    - host: micro-notification.devops2.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: notification-service-service
                port:
                  number: 8084
    - host: micro-auth.devops2.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  number: 8082
    - host: micro-auth.devops2.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  number: 8082
    - host: micro-statistic.devops2.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: statistic-service-service
                port:
                  number: 8088
---



